Feature/srch event subscriber login
sumeetbiswal/project pull request #5
Opened 2023-09-02 17:53 UTC by archanarkamath

This PR includes Authentication of login module.
Other inner pages will be blocked if user is not logged in.
Code standardization also implemented.

2023-09-02 18:03 UTC, sumeetbiswal requested changes

2023-09-02 18:03 UTC, sumeetbiswal commented on modules/custom/login/readme.txt
@archanarkamath  Please delete this file and commit again. we don't need this file.

2023-09-02 18:33 UTC, archanarkamath commented on modules/custom/login/readme.txt
Resolved

2023-09-05 06:17 UTC, sumeetbiswal approved these changes
Approved. looks good.

2023-09-05 06:19 UTC, merged